const mongoose = require("mongoose");

const focusSchema = new mongoose.Schema({
  title: String,
  sub1: String,
  sub2: String,
  sub3: String,
  sub4: String,
  sub5: String,
  sub6: String,
  sub7: String,

  image: String,
  description: String,
  hotel: String,
  turnAround: String,
  serv1: String,
  serv2: String,
  serv3: String,
  serv4: String,
  serv5: String,
  serv6: String,
  serv7: String,
  serv8: String,
  serv9: String,
  serv10: String,
  serv11: String,
  serv12: String,

  //   02
  concept: String,
  conceptText: String,
  concept1: String,
  concept2: String,
  concept3: String,
  concept4: String,
  turnAroundText: String,
  turnAroundFb: String,

  ourServ: String,
  turn1: String,
  turn2: String,
  turn3: String,
  turn4: String,
  turn5: String,
  turn6: String,
  res: String,
  fb1: String,
  fb2: String,
  fb3: String,
  fb4: String,
  fb5: String,
  fb6: String,
  fb7: String,
  fb8: String,
  fb9: String,
  fb10: String,
  fb11: String,
  fb12: String,
  fb13: String,
  fb14: String,
  fb15: String,
  fb16: String,
  fb17: String,
  fb18: String,
  fb19: String,
  restOperation: String,
  resConcept: String,
  op1: String,
  op2: String,
  resFraud: String,
  resFraudConcept: String,
  resServ1: String,
  resServ2: String,
  resServ3: String,
  resServ4: String,
  resServ5: String,
  resServ6: String,
  resServ7: String,
  resDesign: String,
  resDesignConcept: String,
  resDesignServ1: String,
  resDesignServ2: String,
  resDesignServ3: String,
  resDesignServ4: String,
  resDesignServ5: String,
  resDesignServ6: String,
  resDesignServ7: String,
  resDesignServ8: String,
  resDesignServ9: String,

  //   03

  advOp1: String,
  advOp2: String,
  advOp3: String,
  advOp4: String,
  finMngt: String,
  finMngt1: String,
  cons: String,

  adv1: String,
  adv2: String,
  adv3: String,
  adv4: String,
  adv5: String,
  tOperation: String,
  servInd: String,
  servDesc: String,
  ind1: String,
  ind2: String,
  ind3: String,
  ind4: String,
  ind5: String,
  ind6: String,
  ind7: String,
  ind8: String,
  ind9: String,
  ind10: String,
  ind11: String,
  ind12: String,


});

const Focus = mongoose.model("focus", focusSchema);

module.exports = Focus;
